---
- name: Create Rancher cluster via API
  hosts: localhost
  gather_facts: false
  vars:
    rancher_url: "https://192.168.170.45"
    api_token: "token-992sp:phgs5wlpqpf4brjtjdxkqvlsd5tlmn2kgnd2wlj68tmwfdw975n7z8"

  tasks:
    - name: Create OpenStack cluster in Rancher
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          metadata:
            name: "openstack-cluster-2"
            namespace: "fleet-default"
          spec:
            kubernetesVersion: "v1.32.7+rke2r1"
            rkeConfig:
              machinePools: []
        validate_certs: false
        status_code: 201
      register: create_cluster_response

    - name: Show response from Rancher API
      debug:
        var: create_cluster_response.json
